language: generic
services:
  - docker

deploy:
  provider: elasticbeanstalk
  region: "ap-south-1"
  app: "mnd"
  env: "Mnd-env"
  bucket_name: "elasticbeanstalk-ap-south-1-036295041873"
  bucket_path: "mnd"
  on:
   branch: master
  access_key_id: "$AWS_ACCESS_KEY"
  secret_access_key: "$AWS_SECRET_KEY"